### ISSUE TITLE
Console error is thrown during Jest test run

### ISSUE THREAD

**Issue by dtodt** [ngxs-labs/select-snapshot#99]
A console log is thrown during test run.

While running, no error is thrown, and the `ViewSelectSnapshot` works fine.

During tests, it does not fail the test, but this error appears:
```shell
    console.error
      Unhandled Promise rejection: Cannot set property 'factory' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'factory' of undefined
          at decorateView (/_MY_PROJECT_/node_modules/@ngxs-labs/select-snapshot/bundles/ng:/@ngxs-labs/select-snapshot/lib/core/decorators/view-select-snapshot.ts:48:41)
          at /_MY_PROJECT_/node_modules/@ngxs-labs/select-snapshot/bundles/ng:/@ngxs-labs/select-snapshot/lib/core/decorators/view-select-snapshot.ts:37:36
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:386:30)
          at Zone.Object.<anonymous>.Zone.run (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:143:47)
          at /_MY_PROJECT_/node_modules/zone.js/dist/zone.js:891:38
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:421:35)
          at Zone.Object.<anonymous>.Zone.runTask (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:188:51)
          at drainMicroTaskQueue (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:601:39)
          at processTicksAndRejections (internal/process/task_queues.js:93:5) TypeError: Cannot set property 'factory' of undefined
          at decorateView (/_MY_PROJECT_/node_modules/@ngxs-labs/select-snapshot/bundles/ng:/@ngxs-labs/select-snapshot/lib/core/decorators/view-select-snapshot.ts:48:41)
          at /_MY_PROJECT_/node_modules/@ngxs-labs/select-snapshot/bundles/ng:/@ngxs-labs/select-snapshot/lib/core/decorators/view-select-snapshot.ts:37:36
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:386:30)
          at Zone.Object.<anonymous>.Zone.run (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:143:47)
          at /_MY_PROJECT_/node_modules/zone.js/dist/zone.js:891:38
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:421:35)
          at Zone.Object.<anonymous>.Zone.runTask (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:188:51)
          at drainMicroTaskQueue (/_MY_PROJECT_/node_modules/zone.js/dist/zone.js:601:39)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at Object.api.onUnhandledError (../../../node_modules/zone.js/dist/zone.js:690:29)
      at handleUnhandledRejection (../../../node_modules/zone.js/dist/zone.js:713:17)
      at _loop_1 (../../../node_modules/zone.js/dist/zone.js:704:21)
      at Object.api.microtaskDrainDone (../../../node_modules/zone.js/dist/zone.js:708:17)
      at drainMicroTaskQueue (../../../node_modules/zone.js/dist/zone.js:608:22)
```

## I'm submitting a...

<pre><code>
[x] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
</code></pre>

## Current behavior
An error is thrown on console.

## Expected behavior
No error thrown on console.

## Minimal reproduction of the problem with instructions
I've a sidebar component, that works very well with `ViewSelectSnapshot`.

> state
```typescript
export interface SidebarStateInfo {
  display?: boolean;
  position?: string;
}

export interface SidebarStateModel {
  info: SidebarStateInfo;
}

export const defaultSidebarInfo: SidebarStateInfo = {
  position: 'left'
};

export const initialSidebarState: SidebarStateModel = {
  info: defaultSidebarInfo
};

@State<SidebarStateModel>({
  name: 'sidebar',
  defaults: initialSidebarState
})
@Injectable()
export class SidebarState {
  @Selector()
  @ImmutableSelector()
  static getSidebarInfo(state: SidebarStateModel): SidebarStateInfo {
    return state.info;
  }
...
```

> module
```typescript
const imports = [CommonModule, NgxsModule.forFeature([SidebarState]), PrimeSidebarModule];
const components = [SidebarComponent];

@NgModule({
  declarations: [...components],
  exports: [...components],
  imports
})
export class SidebarModule {}
```

> component
```typescript
@Component({
  ...
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SidebarComponent {
  @ViewSelectSnapshot(SidebarState.getSidebarInfo) info: SidebarStateInfo;
...
```

> test
```typescript
describe('SidebarComponent', () => {
  let component: SidebarComponent;
  let fixture: ComponentFixture<SidebarComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        NoopAnimationsModule,
        NgxsModule.forRoot([]),
        NgxsDispatchPluginModule.forRoot(),
        NgxsSelectSnapshotModule.forRoot(),
        SidebarModule
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(SidebarComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

## Environment

<pre><code>
Libs:
- @angular/core version: ^9.1.12
- @ngxs/store version: ^3.7.0
 
For Tooling issues:
- Node version: v14.14.0
- Platform:  MacOs Catalina
</code></pre>

Thanks.

**Comment by arturovt** [comment]
I ain't able to reproduce the issue. Provide a minimal reproducible example please.
